version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3081:3000"
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana

  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    ports:
      - "9116:9116"
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - "9115:9115"
    restart: unless-stopped
    cap_add:
      - NET_RAW
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://USUARIO_BANCO:SENHA_BANCO@IP_BANCO_REMOTO:PORTA_BANCO/NOME_BANCO?schema=SEU_SCHEMA"
    ports:
      - "9187:9187"
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_ENCRYPTION_KEY=GERE-UM-UUID-ALEATORIO

#  alertmanager:
#    image: prom/alertmanager
#    container_name: alertmanager
#    volumes:
#      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
#    command:
#      - '--config.file=/etc/alertmanager/alertmanager.yml'
#    ports:
#      - "9093:9093"
#    restart: unless-stopped

volumes:
  n8n_data:
  grafana-storage:
  portainer_data:
  loki-data:
